mariaDB4j:
  port: 3307

server:
  port: 8080

spring:
  datasource:
#    url: jdbc:mysql://docker-mysql/test # Docker config
    url: jdbc:mysql://localhost:3307/test
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
    locations: classpath:db/migration/
#    url: jdbc:mysql://docker-mysql:3307/test # Docker config
    url: jdbc:mysql://localhost:3307/test
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeout: 30000

## Redis Config
#spring.cache.type=redis
#spring.redis.host=localhost
#spring.redis.port=6379