mariaDB4j:
  port: 3307

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?username=root&password=
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration/
    url: jdbc:mysql://localhost:3307/test?username=root&password=